apiVersion: example.itd27m01.com/v1alpha1
kind: MyCRD
metadata:
  labels:
    app.kubernetes.io/name: mycrd
    app.kubernetes.io/instance: mycrd-sample
    app.kubernetes.io/part-of: kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-operator
  name: mycrd-sample
spec:
  # TODO(user): Add fields here
